### ISSUE TITLE
Migration Bug

### ISSUE THREAD

**Issue by jmbarne3** [UCF/Search-Service-Django#183]
When migrating the database for the first time, the following error occurs:

```
django.db.utils.OperationalError: (1054, "Unknown column 'teledata_combinedteledata.active' in 'field list'")
```

The error is caused by our call to the [`update_data`](https://github.com/UCF/Search-Service-Django/blob/master/teledata/migrations/0009_auto_20191108_1358.py#L10) method during the `0009` migration for teledata. The code relies on a schema that existed at the time of the migration, but no longer exists now. The best thing to do is probably just to remove this step and add an instruction for the setup of the project to add a call to the `update_data` method manually at some point after the initial migrations are finished.

**Comment by cjg89** [comment]
This was resolved in v2.3.1 (see https://github.com/UCF/Search-Service-Django/pull/267).  Closing.
