### ISSUE TITLE
Identify Endpoints for Each Dataset

### ISSUE THREAD

**Issue by jmbarne3** [UCF/Search-Service-Django#83]
Identify endpoints, search and pagination parameters for the following datasets:

* Images
* Programs
* Events
* News
* Locations (Buildings)
* Teledata (Staff members)

**Comment by jmbarne3** [comment]
## Images 

Where: Search Service
Endpoint: `api/v1/images/search/`
Query: `search` (not implemented yet)
Pagination: `limit` and `offset`. Page information can be found in the result meta.

## Programs

Where: Search Service
Endpoint: `api/v1/programs/search/`
Query: `search`
Pagination: `limit` and `offset`

## Events

Where: Event System
Endpoint: ??? (may not exist yet)
Query: ???
Pagination: ???

## News

Where: UCF Today
Endpoint: `wp-json/wp/v2/posts/`
Query: `search`
Pagination: `per_page` and `offset`

## Locations

Where: Search Service
Endpoint: `api/v1/teledata/buildings/`
Query: `search` (not implemented yet)
Pagination: `limit` and `offset`

## Teledata

Where: Search Service
Endpoints: `api/v1/teledata/`*
Query: `search`
Pagination: `limit` and `offset`

* If we only want staff, the `use=staff` parameter can be added. If we want staff, organizations and departments, leave this parameter off.

**Comment by cjg89** [comment]
Did we decide to include announcements as an endpoint?
